version: 2
jobs:
  build:
    docker:
      - image: norionomura/docker-swift-updater
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: swift lint
          command: |
            cd ~
            git clone https://github.com/realm/SwiftLint
            cd SwiftLint
            make
            cd ~/repo
            ~/SwiftLint/.build/x86_64-unknown-linux/release/swiftlint --config ./.swiftlint/swiftlint.yml
